# ================================================
# DOCKERFILE =====================================
# ================================================

# ------------------------------------------------
# VERSION ----------------------------------------
# ------------------------------------------------
version: '3'

# ------------------------------------------------
# SERVICES ---------------------------------------
# ------------------------------------------------
services:

  # ----------------------------------------------
  # NGINX-PROXY ----------------------------------
  # ----------------------------------------------
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
    logging:
      driver: "none"

  # ----------------------------------------------
  # JUPYTER (LAB) --------------------------------
  # ----------------------------------------------
  jupyter:
    image: dldc
    # user: $UID
    volumes:
      - ./shared:/shared
    environment:
      - VIRTUAL_HOST=jupyter.${EXTERNAL_HOST}
      - VIRTUAL_PORT=8888
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - JUPYTER_PASSWORD_HASH=${JUPYTER_PASSWORD_HASH}
    ports:
      - "8888:8888"
      - "8097:8097"
    command: bash /root/.scripts/run_jupyter_lab.sh

  # ----------------------------------------------
  # TENSORBOARD ----------------------------------
  # ----------------------------------------------
  tensorboard:
    image: dldc
    # user: $UID
    volumes:
      - ./shared:/shared
    environment:
      - VIRTUAL_HOST=tensorboard.${EXTERNAL_HOST}
      - VIRTUAL_PORT=6006
    ports:
      - "6006:6006"
    command: tensorboard --logdir=/shared/tensorboard --reload_interval=1 --port 6006

