name: dldc
channels:
  - conda-forge
  - pytorch
  - fastai
dependencies:
  - pip
  - pytorch
  - torchvision
  - cuda100
  - fastprogress
  - fastai
  - jupyter
  - jupyterlab
  - cudatoolkit=10.0
  - pip:
      - nvidia-ml-py3
      - dataclasses
